input {
  kafka {
    bootstrap_servers => "${KAFKA_BROKERS}"
    topics => ["${KAFKA_TOPIC}"]
    group_id => "logstash-consumer-logs"
    codec => "json"
    auto_offset_reset => "earliest"
    decorate_events => true
  }
}

filter {
  if [msg] {
    mutate { rename => { "msg" => "message" } }
  }

  if [ts] {
    date { match => ["ts", "ISO8601", "yyyy-MM-dd HH:mm:ss,SSS", "UNIX_MS"] target => "@timestamp" }
  }

  if [level] { mutate { lowercase => ["level"] } }
  if ![service] { mutate { add_field => { "service" => "fake-app" } } }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
    action => "index"
  }

  stdout { codec => rubydebug }
}
